# Generated by Django 4.2.1 on 2023-09-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_order_date_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
