# Generated by Django 4.2.1 on 2023-09-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_customer_user_remove_supplier_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_price',
        ),
    ]
