# Generated by Django 4.2.1 on 2023-10-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_stock_price_stock_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=100),
        ),
    ]
