# Generated by Django 4.2.1 on 2023-10-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_stock_order_price_remove_stock_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.product'),
        ),
    ]
