# Generated by Django 4.2.1 on 2023-10-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_orderitem_product_alter_purchase_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
    ]
