# Generated by Django 4.2.1 on 2023-10-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_stock_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mobile_no',
            field=models.IntegerField(default=True),
        ),
    ]
